//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqtoDatasetInEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAggregationTable
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> EmployeeSalary { get; set; }
        public string DeptName { get; set; }
    
        public virtual EmpAggregationTable EmpAggregationTable1 { get; set; }
        public virtual EmpAggregationTable EmpAggregationTable2 { get; set; }
    }
}
