//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqtoDatasetInEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public short EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> EmployeeSalary { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual DepartmentTable DepartmentTable { get; set; }
    }
}
